name: CI Dependencies
on: [push, pull_request]
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.2.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
