name: CI Dependencies
on: [push, pull_request]

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
